### ISSUE TITLE
FR: Unlink suggestions for reducing the number of excessive links to a page

### ISSUE THREAD

**Issue by xenohunter** [deepfates/silicon#3]
Given [Visa's idea](https://twitter.com/visakanv/status/1605923613638631424) (or probably not his but whatever) that if you link each page to each other, it's as if you don't link any pages at all, it would be great to have an opportunity to get a list of linked pages, sorted by relevance (and you can switch between ascending and descending order). You can then remove unneeded links, whether they are too relevant or not relevant enough.

**Comment by deepfates** [comment]
what does this mean exactly? currently the sidebar reveals the top 50 results, I think? would you like it to be more interactive and editable or am I misreading

**Comment by xenohunter** [comment]
Let me describe a specific use case (mine): in my first year of writing things in Obsidian, I made too many links where none were needed (i.e. often linked a page just because the word from its name was mentioned). Now I want to filter backlinks for each page and leave only those that are the most distant but still relevant. Because too close links are redundant due to their proximity and irrelevant links are just noise.

So I'd love the sidebar to have a setting/checkbox that allows to filter out entries that are not backlinks.

**Comment by deepfates** [comment]
Okay, I think I understand! This would remove from the list pages that link to the current document? This seems like it might be a good default actually, as those are already listed in the Backlinks and Outlinks panels. Silicon would then only be suggesting things that would be overlooked actually. I will try to implement this today

**Comment by deepfates** [comment]
Okay this should be changed in the [latest release](https://github.com/deepfates/silicon/releases/tag/1.0.1)! Hopefully should "just work" but if it doesn't you might have to Wipe Index. Closing this for now but let me know if there's any bugs
