### ISSUE TITLE
Failed to load plugin obsidian silicon

### ISSUE THREAD

**Issue by MarlonKr** [deepfates/silicon#4]
Whenever I try to open the plugin "Obsidian Silicon," it immediately deactivates and displays an error message stating "Failed to load plugin obsidian silicon." I am currently using Obsidian version 1.1.9.

**Comment by ostrichery** [comment]
Had the same issue. Also on Version 1.1.9

**Comment by richpav** [comment]
Don't download the source code archive. Instead, Create a folder in your plugin folder called Silicon. Into that folder, download the files main.js, manifest.json and styles.css. Then restart Obsidian, paste in your API key, etc.

**Comment by deepfates** [comment]
did this work out? should I put it in the README

**Comment by pentekostos** [comment]
I ran into the same issue and @richpav's solution worked. I was confused because it said to extract the files in the README, and I've never installed a plugin manually before.

**Comment by deepfates** [comment]
yes I just tested it myself from the mobile app and this also seemed to
work. I will change the instructions to reflect this thanks everyone

**Comment by ostrichery** [comment]
yup worked for me!

**Comment by deepfates** [comment]
I have changed the instructions in the readme to match! thank you everyone for your help
