### ISSUE TITLE
FR: Exclude paths from indexing

### ISSUE THREAD

**Issue by phkus** [deepfates/silicon#5]
I'm getting a lot of noisy results from older project notes and Readwise exports that mainly contain highlights. These files often don't have meaningful titles, which makes the results in the sidebar less useful.
I could create a new vault with more curated content, but I still want to have some reference files, so I'd prefer if I could limit which folders the results come from.

Thanks for the plugin, this looks really exciting!

**Comment by deepfates** [comment]
thanks for this feedback! it's a good idea, I'll implement it this week. probably just a list of folders to not index for now, but some day may be useful to restrict indexing within each folder (or some other custom setup). I'm also planning to add hover tips to the sidebar results soon, so you'll be able to get more information than just the title

**Comment by deepfates** [comment]
Okay, this is in [1.0.1](https://github.com/deepfates/silicon/releases/tag/1.0.1)! Any folder listed in the box in Settings will be ignored, along with all its children.
